### ISSUE TITLE
Flickerplate fade transition problem

### ISSUE THREAD

**Issue by AlexandruDoda** [chrishumboldt/Flickerplate#45]
Hi! I am trying to use the jquery-fade transition for my slider and here's what happens:
https://www.dropbox.com/s/rnaf8nfssjpyxdi/flickerplate-error.mov?dl=0

The default transition works fine (the slide) but if I try to use jquery-fade or transition-fade, only the first slide works and the rest show up blank. Also, it seems the DOM structure gets altered somehow since those social icons disappear.

Any ideas? Thanks! I really need it for the project I'm working on so any help or possible fixes are highly appreciated.

Cheers!
Alexandru Doda

**Comment by chrishumboldt** [comment]
Hey Alexandru

The jQuery animation options have been deprecated for a few reasons:

1. They were adding very little value to the transitions.
2. Browsers are handling CSS transitions much better these days.
3. Was tricky to maintain with jQuery updates.

Keep Well
C
