### ISSUE TITLE
Dynamically remove flickerplate from webpage

### ISSUE THREAD

**Issue by EricArc** [chrishumboldt/Flickerplate#58]
Hi,

I am trying to remove the flickerplate element from the web page via JS. Unfortunately after I do that, the flickerAutoFlick method keeps firing producing an error every interval. I may be missing something here but I can't find a way to stop the autoflick before disposing of the flickerplate object?

Regards
Eric

**Comment by chrishumboldt** [comment]
Hi Eric

With the latest release you can do this. You will need to initialise the component differently now so take a moment to read the updated documentation.

Let me know if you are still having an issues.
